// Central source of truth for AI tool cards
// Used by best-of, industries, and ai-tools listing pages

export interface AIToolCard {
  slug: string;
  name: string;
  shortDesc: string;
  logo: { bg: string; text: string };
  editorialRating: number;
  category: "Interior Design" | "Architecture" | "Construction" | "Real Estate" | "Furniture" | "Cross-niche";
  pricing: string;
  pricingTier: "Free" | "Freemium" | "Paid" | "Custom";
  bestFor: string;
  isFeatured: boolean;
  affiliateHref: string;
  tags: string[];
}

export const aiToolCards: AIToolCard[] = [
  // ── Interior Design ────────────────────────────────────────────
  {
    slug: "planner-5d",
    name: "Planner 5D",
    shortDesc: "AI-powered floor plan and 3D design tool for photorealistic room visualization.",
    logo: { bg: "bg-green-600", text: "P5" },
    editorialRating: 4.8,
    category: "Interior Design",
    pricing: "From $6.99/month",
    pricingTier: "Freemium",
    bestFor: "Interior Designers, Homeowners",
    isFeatured: true,
    affiliateHref: "#",
    tags: ["productivity", "ai-image-generation"],
  },
  {
    slug: "roomgpt",
    name: "RoomGPT",
    shortDesc: "Generate interior design ideas instantly from room photos using AI.",
    logo: { bg: "bg-gray-900", text: "RG" },
    editorialRating: 4.7,
    category: "Interior Design",
    pricing: "From $9.99/month",
    pricingTier: "Freemium",
    bestFor: "Freelancers, Homeowners",
    isFeatured: false,
    affiliateHref: "#",
    tags: ["ai-image-generation", "no-code"],
  },
  {
    slug: "coohom",
    name: "Coohom",
    shortDesc: "Professional 3D interior design and rendering platform with real-time collaboration.",
    logo: { bg: "bg-blue-500", text: "C" },
    editorialRating: 4.7,
    category: "Interior Design",
    pricing: "From $15/month",
    pricingTier: "Free",
    bestFor: "Design Studios, Interior Designers",
    isFeatured: false,
    affiliateHref: "#",
    tags: ["ai-image-generation", "productivity"],
  },
  {
    slug: "homestyler",
    name: "Homestyler",
    shortDesc: "User-friendly 3D interior design tool with AI and a huge model library.",
    logo: { bg: "bg-gradient-to-br from-red-400 via-yellow-400 to-green-400", text: "H" },
    editorialRating: 4.6,
    category: "Interior Design",
    pricing: "From $4.90/month",
    pricingTier: "Freemium",
    bestFor: "Freelancers, Homeowners",
    isFeatured: false,
    affiliateHref: "#",
    tags: ["ai-image-generation", "no-code"],
  },
  {
    slug: "foyr-neo",
    name: "Foyr Neo",
    shortDesc: "AI-powered interior design software for space planning, 3D rendering, and presentations.",
    logo: { bg: "bg-gray-900", text: "FN" },
    editorialRating: 4.8,
    category: "Interior Design",
    pricing: "From $30/month",
    pricingTier: "Paid",
    bestFor: "Interior Designers, Design Studios",
    isFeatured: false,
    affiliateHref: "#",
    tags: ["ai-image-generation", "productivity"],
  },

  // ── Architecture ───────────────────────────────────────────────
  {
    slug: "vizcom",
    name: "Vizcom",
    shortDesc: "AI-powered concept sketching and rendering tool for architects and designers.",
    logo: { bg: "bg-[#2d5cf3]", text: "VZ" },
    editorialRating: 4.8,
    category: "Architecture",
    pricing: "From $X/month",
    pricingTier: "Freemium",
    bestFor: "Architects, Concept Designers",
    isFeatured: true,
    affiliateHref: "#",
    tags: ["ai-image-generation", "prompt-engineering"],
  },
  {
    slug: "autodesk-forma",
    name: "Autodesk Forma",
    shortDesc: "Data-driven site and climate analysis tool for early-stage architectural planning.",
    logo: { bg: "bg-gray-900", text: "AF" },
    editorialRating: 4.7,
    category: "Architecture",
    pricing: "From $X/month",
    pricingTier: "Freemium",
    bestFor: "Architects, Urban Planners",
    isFeatured: false,
    affiliateHref: "#",
    tags: ["productivity", "ai-for-business"],
  },
  {
    slug: "testfit",
    name: "TestFit",
    shortDesc: "AI feasibility and site planning tool that generates building layouts in seconds.",
    logo: { bg: "bg-gray-700", text: "TF" },
    editorialRating: 4.7,
    category: "Architecture",
    pricing: "From $X/month",
    pricingTier: "Free",
    bestFor: "Developers, Architects",
    isFeatured: false,
    affiliateHref: "#",
    tags: ["productivity", "ai-for-business"],
  },
  {
    slug: "midjourney",
    name: "Midjourney",
    shortDesc: "AI image generation for photorealistic architectural concept visualizations.",
    logo: { bg: "bg-black", text: "MJ" },
    editorialRating: 4.6,
    category: "Architecture",
    pricing: "From $10/month",
    pricingTier: "Freemium",
    bestFor: "Architects, Interior Designers",
    isFeatured: false,
    affiliateHref: "#",
    tags: ["midjourney", "ai-image-generation", "prompt-engineering"],
  },
  {
    slug: "arkdesign-ai",
    name: "ArkDesign AI",
    shortDesc: "AI-assisted architectural design tool for layout optimization and space planning.",
    logo: { bg: "bg-[#6b8cfb]", text: "AD" },
    editorialRating: 4.6,
    category: "Architecture",
    pricing: "From $X/month",
    pricingTier: "Paid",
    bestFor: "Architects, Design Firms",
    isFeatured: false,
    affiliateHref: "#",
    tags: ["ai-image-generation", "productivity"],
  },
  {
    slug: "archicad-ai",
    name: "Archicad AI",
    shortDesc: "AI-powered BIM software for intelligent building design, collaboration, and documentation.",
    logo: { bg: "bg-blue-700", text: "AC" },
    editorialRating: 4.8,
    category: "Architecture",
    pricing: "From $180/month",
    pricingTier: "Freemium",
    bestFor: "Architects, Design Firms",
    isFeatured: true,
    affiliateHref: "#",
    tags: ["productivity", "ai-for-business"],
  },
  {
    slug: "d5-render",
    name: "D5 Render",
    shortDesc: "Real-time AI rendering engine that converts 3D models into photorealistic visuals instantly.",
    logo: { bg: "bg-purple-600", text: "D5" },
    editorialRating: 4.8,
    category: "Architecture",
    pricing: "From $30/month",
    pricingTier: "Freemium",
    bestFor: "Architects, Visualization Studios",
    isFeatured: false,
    affiliateHref: "#",
    tags: ["ai-image-generation", "productivity"],
  },
  {
    slug: "veras",
    name: "Veras",
    shortDesc: "AI rendering tool that transforms architectural sketches and BIM models into photorealistic visuals.",
    logo: { bg: "bg-teal-500", text: "V" },
    editorialRating: 4.7,
    category: "Architecture",
    pricing: "From $25/month",
    pricingTier: "Paid",
    bestFor: "Architects, Urban Planners",
    isFeatured: false,
    affiliateHref: "#",
    tags: ["ai-image-generation", "productivity"],
  },
  {
    slug: "twinmotion-ai",
    name: "Twinmotion AI",
    shortDesc: "Real-time 3D visualization software with AI for stunning architectural presentations.",
    logo: { bg: "bg-blue-500", text: "TM" },
    editorialRating: 4.6,
    category: "Architecture",
    pricing: "From $499/year",
    pricingTier: "Freemium",
    bestFor: "Architects, Visualization Studios",
    isFeatured: false,
    affiliateHref: "#",
    tags: ["ai-image-generation", "productivity"],
  },

  // ── Construction ───────────────────────────────────────────────
  {
    slug: "buildots",
    name: "Buildots",
    shortDesc: "AI construction monitoring platform that compares site progress against BIM models in real time.",
    logo: { bg: "bg-[#f27313]", text: "BD" },
    editorialRating: 4.8,
    category: "Construction",
    pricing: "Custom",
    pricingTier: "Custom",
    bestFor: "General Contractors, Project Managers",
    isFeatured: true,
    affiliateHref: "#",
    tags: ["automation", "productivity", "ai-for-business"],
  },
  {
    slug: "openspace",
    name: "OpenSpace",
    shortDesc: "360° site capture and AI analysis tool that automatically documents every corner of your job site.",
    logo: { bg: "bg-gray-900", text: "OS" },
    editorialRating: 4.7,
    category: "Construction",
    pricing: "Custom",
    pricingTier: "Custom",
    bestFor: "Site Engineers, Project Managers",
    isFeatured: false,
    affiliateHref: "#",
    tags: ["automation", "productivity"],
  },
  {
    slug: "alice-technologies",
    name: "ALICE Technologies",
    shortDesc: "AI-driven construction simulation and schedule optimization for the fastest, lowest-cost build path.",
    logo: { bg: "bg-gray-700", text: "AT" },
    editorialRating: 4.6,
    category: "Construction",
    pricing: "Custom",
    pricingTier: "Custom",
    bestFor: "General Contractors, Planners",
    isFeatured: false,
    affiliateHref: "#",
    tags: ["automation", "ai-for-business"],
  },
  {
    slug: "procore-ai",
    name: "Procore AI",
    shortDesc: "AI-enhanced construction project management covering scheduling, budgets, and field collaboration.",
    logo: { bg: "bg-orange-700", text: "PA" },
    editorialRating: 4.6,
    category: "Construction",
    pricing: "From $X/month",
    pricingTier: "Freemium",
    bestFor: "General Contractors, Project Managers",
    isFeatured: false,
    affiliateHref: "#",
    tags: ["automation", "ai-for-business", "productivity"],
  },
  {
    slug: "pillar",
    name: "Pillar",
    shortDesc: "AI-powered quality and safety inspection tool for construction sites.",
    logo: { bg: "bg-[#fbac6a]", text: "PL" },
    editorialRating: 4.5,
    category: "Construction",
    pricing: "From $X/month",
    pricingTier: "Paid",
    bestFor: "Site Engineers, Quality Managers",
    isFeatured: false,
    affiliateHref: "#",
    tags: ["automation", "productivity"],
  },
  {
    slug: "plangrid",
    name: "PlanGrid",
    shortDesc: "Field management tool by Autodesk for drawings, punch lists, and RFIs on any device.",
    logo: { bg: "bg-emerald-600", text: "PG" },
    editorialRating: 4.5,
    category: "Construction",
    pricing: "From $39/month",
    pricingTier: "Freemium",
    bestFor: "Site Engineers, Subcontractors",
    isFeatured: false,
    affiliateHref: "#",
    tags: ["productivity", "workflow"],
  },

  // ── Real Estate ────────────────────────────────────────────────
  {
    slug: "reimaginehome",
    name: "REimagineHome",
    shortDesc: "AI virtual staging tool that transforms empty rooms into stunning furnished spaces in seconds.",
    logo: { bg: "bg-[#8c21f1]", text: "RH" },
    editorialRating: 4.8,
    category: "Real Estate",
    pricing: "From $29/month",
    pricingTier: "Freemium",
    bestFor: "Real Estate Agents, Brokerages",
    isFeatured: true,
    affiliateHref: "#",
    tags: ["ai-image-generation", "ai-for-business"],
  },
  {
    slug: "offrs",
    name: "Offrs",
    shortDesc: "Predictive analytics platform to identify motivated sellers before they hit the market.",
    logo: { bg: "bg-gray-900", text: "OF" },
    editorialRating: 4.7,
    category: "Real Estate",
    pricing: "Custom",
    pricingTier: "Custom",
    bestFor: "Real Estate Agents, Teams",
    isFeatured: false,
    affiliateHref: "#",
    tags: ["ai-for-business", "automation"],
  },
  {
    slug: "lofty-ai",
    name: "Lofty AI",
    shortDesc: "AI-powered CRM that nurtures and converts real estate leads automatically.",
    logo: { bg: "bg-gray-700", text: "LA" },
    editorialRating: 4.6,
    category: "Real Estate",
    pricing: "From $X/month",
    pricingTier: "Freemium",
    bestFor: "Real Estate Agents, Teams",
    isFeatured: false,
    affiliateHref: "#",
    tags: ["ai-for-business", "automation"],
  },
  {
    slug: "structurely",
    name: "Structurely",
    shortDesc: "AI chatbot that qualifies and follows up with real estate leads via SMS and email 24/7.",
    logo: { bg: "bg-purple-700", text: "ST" },
    editorialRating: 4.6,
    category: "Real Estate",
    pricing: "Custom",
    pricingTier: "Custom",
    bestFor: "Real Estate Agents, New Agents",
    isFeatured: false,
    affiliateHref: "#",
    tags: ["ai-agents", "automation", "ai-for-business"],
  },
  {
    slug: "zillow-showcase",
    name: "Zillow Showcase",
    shortDesc: "AI-powered listing showcase tool that creates immersive property tours to attract buyers.",
    logo: { bg: "bg-[#c281fa]", text: "ZS" },
    editorialRating: 4.5,
    category: "Real Estate",
    pricing: "From $X/month",
    pricingTier: "Paid",
    bestFor: "Real Estate Agents, Brokerages",
    isFeatured: false,
    affiliateHref: "#",
    tags: ["ai-image-generation", "ai-for-business"],
  },
  {
    slug: "copy-ai",
    name: "Copy.ai",
    shortDesc: "AI writing tool that generates property descriptions, email campaigns, and social content.",
    logo: { bg: "bg-blue-600", text: "C" },
    editorialRating: 4.7,
    category: "Real Estate",
    pricing: "From $36/month",
    pricingTier: "Freemium",
    bestFor: "Real Estate Agents, Property Managers",
    isFeatured: false,
    affiliateHref: "#",
    tags: ["ai-writing", "ai-for-business"],
  },
  {
    slug: "housecanary",
    name: "HouseCanary",
    shortDesc: "AI-powered property valuation and market analytics platform for accurate home price estimates.",
    logo: { bg: "bg-purple-600", text: "HC" },
    editorialRating: 4.7,
    category: "Real Estate",
    pricing: "From $79/month",
    pricingTier: "Paid",
    bestFor: "Agents, Investors, Brokerages",
    isFeatured: false,
    affiliateHref: "#",
    tags: ["ai-for-business", "productivity"],
  },
  {
    slug: "manychat",
    name: "ManyChat",
    shortDesc: "AI chatbot platform that automates lead capture and follow-up across Instagram, Facebook, and SMS.",
    logo: { bg: "bg-blue-500", text: "MC" },
    editorialRating: 4.6,
    category: "Real Estate",
    pricing: "From $15/month",
    pricingTier: "Freemium",
    bestFor: "Real Estate Agents, New Agents",
    isFeatured: false,
    affiliateHref: "#",
    tags: ["automation", "ai-agents", "ai-for-business"],
  },

  // ── Furniture ──────────────────────────────────────────────────
  {
    slug: "roomvo",
    name: "Roomvo",
    shortDesc: "AI room visualizer that lets shoppers see furniture and flooring in their own space instantly.",
    logo: { bg: "bg-blue-600", text: "R" },
    editorialRating: 4.8,
    category: "Furniture",
    pricing: "Custom",
    pricingTier: "Custom",
    bestFor: "Furniture Retailers, E-commerce",
    isFeatured: true,
    affiliateHref: "#",
    tags: ["ai-image-generation", "no-code"],
  },
  {
    slug: "zakeke",
    name: "Zakeke",
    shortDesc: "3D product configurator and AI visualization tool for furniture customization and ecommerce.",
    logo: { bg: "bg-purple-600", text: "Z" },
    editorialRating: 4.7,
    category: "Furniture",
    pricing: "From $79/month",
    pricingTier: "Paid",
    bestFor: "Furniture Manufacturers, Retailers",
    isFeatured: false,
    affiliateHref: "#",
    tags: ["ai-image-generation", "ai-for-business"],
  },
  {
    slug: "photoroom",
    name: "Photoroom",
    shortDesc: "AI photo editor for creating professional product images and marketing visuals in seconds.",
    logo: { bg: "bg-[#4F46E5]", text: "PR" },
    editorialRating: 4.7,
    category: "Furniture",
    pricing: "From $13/month",
    pricingTier: "Freemium",
    bestFor: "Furniture Retailers, Marketing Teams",
    isFeatured: false,
    affiliateHref: "#",
    tags: ["ai-image-generation", "no-code"],
  },

  // ── Cross-niche ────────────────────────────────────────────────
  {
    slug: "canva-ai",
    name: "Canva AI",
    shortDesc: "AI-powered design platform for creating stunning marketing materials, flyers, and social graphics.",
    logo: { bg: "bg-[#0CC0DF]", text: "CA" },
    editorialRating: 4.9,
    category: "Cross-niche",
    pricing: "From $13/month",
    pricingTier: "Freemium",
    bestFor: "Agents, Retailers, Designers, Marketers",
    isFeatured: false,
    affiliateHref: "#",
    tags: ["ai-image-generation", "no-code", "ai-writing"],
  },
  {
    slug: "jasper",
    name: "Jasper",
    shortDesc: "AI content writing platform for generating marketing copy, blog posts, and ad campaigns.",
    logo: { bg: "bg-orange-500", text: "J" },
    editorialRating: 4.6,
    category: "Cross-niche",
    pricing: "From $39/month",
    pricingTier: "Paid",
    bestFor: "Marketing Teams, Content Creators",
    isFeatured: false,
    affiliateHref: "#",
    tags: ["ai-writing", "ai-for-business"],
  },
  {
    slug: "involve-me",
    name: "involve.me",
    shortDesc: "Interactive content platform for building quizzes, surveys, and forms that convert visitors into leads.",
    logo: { bg: "bg-indigo-600", text: "IM" },
    editorialRating: 4.4,
    category: "Cross-niche",
    pricing: "From $36/month",
    pricingTier: "Paid",
    bestFor: "Marketing Teams, Lead Generation Agencies",
    isFeatured: false,
    affiliateHref: "https://www.involve.me/?red=smartaa4fdcb",
    tags: ["ai-for-business", "no-code", "productivity"],
  },
  {
    slug: "alli-ai",
    name: "Alli AI",
    shortDesc: "Automated SEO platform that finds and deploys on-page fixes directly to your site.",
    logo: { bg: "bg-orange-600", text: "AA" },
    editorialRating: 4.3,
    category: "Cross-niche",
    pricing: "From $249/month",
    pricingTier: "Paid",
    bestFor: "SEO Agencies, Ecommerce Sites",
    isFeatured: false,
    affiliateHref: "https://www.alliai.com/?red=smartaa4fdcb",
    tags: ["ai-for-business", "automation", "productivity"],
  },
];
