export interface CaseStudyContentBlock {
  type: "paragraph" | "heading" | "image" | "quote" | "stat-table" | "cta";
  text?: string;
  level?: 2 | 3; // cho heading
  src?: string; // cho image
  alt?: string;
  caption?: string;
  rows?: { label: string; before: string; after: string }[]; // cho stat-table
  ctaText?: string;
  ctaLink?: string;
}

export interface CaseStudy {
  slug: string;
  title: string;
  industry: string;
  businessSize: string;
  market: string;
  timeFrame: string;
  thumbnail: string;
  heroImage?: string;
  excerpt: string;
  content: CaseStudyContentBlock[];
  tags: string[];
  readingTime: string;
  publishedDate: string;
}

export const caseStudies: CaseStudy[] = [
  {
    slug: "furniture-ai-tools",
    title: "How a Small Furniture Studio Cut Product Photo Costs by 70% Using AI",
    industry: "Furniture & Home Décor",
    businessSize: "8-person studio",
    market: "B2C + B2B, Europe",
    timeFrame: "3 months",
    thumbnail: "/images/case-studies/furniture-ai-tools-thumb.webp",
    heroImage: "/images/case-studies/furniture-ai-tools-hero.webp",
    excerpt:
      "A boutique furniture brand replaced expensive photography and 3D rendering with AI tools, cutting content production costs by 70% and shortening their sales cycle from 18 to 6 days.",
    tags: ["AI tools for furniture", "AI product photography", "room staging AI", "furniture copywriting"],
    readingTime: "6 min",
    publishedDate: "2026-06-16",
    content: [
      { type: "paragraph", text: "Running a small furniture studio sounds romantic — beautiful craftsmanship, happy customers, a growing brand. But behind every product launch, there's a logistical nightmare that eats through budgets and delays timelines faster than anything else: content production." },
      { type: "paragraph", text: "For Lumera Studio (name changed), a boutique furniture brand based in the Netherlands specializing in solid wood sofas and modular shelving, this problem came to a head in early 2024." },
      { type: "heading", level: 2, text: "The problem nobody talks about" },
      { type: "paragraph", text: "They had just finished their Spring collection — 14 new pieces, each in 3 colorways. That's 42 product variants that needed professional lifestyle photography, 3D room visualizations, and product descriptions in three languages." },
      { type: "image", src: "/images/case-studies/furniture-ai-tools-1.webp", alt: "Furniture workshop with wood materials", caption: "Lumera Studio's workshop, where solid wood pieces are crafted by hand" },
      { type: "paragraph", text: "Their usual photographer charged 900 euros per day. The 3D rendering studio had a 5-day turnaround per piece. The math was brutal: an estimated 18,000 euros and 6 weeks just to get the collection live online." },
      { type: "heading", level: 2, text: "The turning point" },
      { type: "paragraph", text: "Two weeks before the planned launch, their photographer cancelled due to a family emergency. Instead of pushing the deadline back, the studio's operations manager decided to try AI tools — something she'd been skeptical about for a long time." },
      { type: "heading", level: 2, text: "The 3 AI tools that changed their workflow" },
      { type: "paragraph", text: "Tool 1 — AI image generation solved their photography cost problem. They took existing white-background product shots and generated realistic lifestyle environments around them, dropping photography cost per product from around 600 euros to under 90 euros." },
      { type: "image", src: "/images/case-studies/furniture-ai-tools-2.webp", alt: "Modern living room with sofa", caption: "AI-generated lifestyle staging replaced traditional studio photography" },
      { type: "paragraph", text: "Tool 2 — AI room staging solved the 'what will this look like in my home' question that was the biggest friction point in their sales process. Customers upload a photo of their room, the studio drops in the product, and a visualization is ready in minutes instead of 4-5 business days." },
      { type: "paragraph", text: "Tool 3 — AI copywriting solved the content bottleneck across 42 product variants in 3 languages, reducing content production time by 80 percent." },
      { type: "heading", level: 2, text: "The numbers, three months later" },
      { type: "stat-table", rows: [
        { label: "Photography cost per collection", before: "12,000-18,000 EUR", after: "2,100-3,500 EUR" },
        { label: "Time to deliver client visualization", before: "4-5 business days", after: "20-30 minutes" },
        { label: "Content production time (full catalogue)", before: "5-6 weeks", after: "1.5 weeks" },
        { label: "Average sales cycle (B2C, 800 EUR+)", before: "18 days", after: "6 days" },
      ]},
      { type: "quote", text: "The images are indistinguishable from our old photography. The only thing AI can't replace is the actual craftsmanship in the product itself — and that's exactly where our value is." },
      { type: "heading", level: 2, text: "What this means for your furniture business" },
      { type: "paragraph", text: "If you're running a furniture studio, retail operation, or manufacturing business, the entry point to AI tools is lower than you think. This isn't about replacing your team — it's about letting them focus on judgment and creativity rather than repetitive production work." },
      { type: "cta", ctaText: "Browse AI tools for furniture businesses", ctaLink: "/best-of/interior-design" },
    ]
  },
  {
    slug: "case-study-architecture-archvision",
    title: "How ArchVision Cut Client Revision Cycles from 3 Weeks to 3 Days Using AI Rendering",
    industry: "Architecture",
    businessSize: "6-person studio",
    market: "Residential + boutique commercial, Western Europe",
    timeFrame: "4 months",
    thumbnail: "/images/case-studies/archvision-case-study-thumbnail.webp",
    heroImage: "/images/case-studies/archvision-case-study-1.webp",
    excerpt:
      "A six-person architecture studio replaced slow, expensive external rendering with AI tools inside Revit, cutting concept approval time from 3-4 weeks to 3-4 days and lifting client approval rates from 40% to 73%.",
    tags: ["AI tools for architects", "AI rendering software", "Veras AI", "architecture visualization", "client approval workflow"],
    readingTime: "6 min",
    publishedDate: "2026-06-20",
    content: [
      { type: "paragraph", text: "For a small architecture studio, every project is a relationship. You spend weeks developing a concept, refining massing, thinking through materiality — and then you sit a client down in front of a set of technical drawings and renders and watch their face go politely blank." },
      { type: "paragraph", text: "That was the recurring experience at ArchVision (name changed), a six-person studio based in Amsterdam specializing in residential extensions and boutique commercial fit-outs. Their work was well-regarded. Their clients were engaged. But the feedback loop between concept and approval had become painful." },
      { type: "heading", level: 2, text: "The Problem With Waiting Three Weeks for a \"No\"" },
      { type: "paragraph", text: "The typical cycle: develop a concept over two to three weeks, produce renders in Revit and send to an external rendering studio, wait five to seven business days for output, present to client, receive feedback like \"I'm not sure about the feel of it,\" revise, repeat. A single concept approval was taking three to four weeks on average — and eating a significant portion of the project's profitability before construction had even started." },
      { type: "paragraph", text: "The studio principal described it directly: \"We were spending enormous energy on beautiful work that clients couldn't emotionally connect with until very late in the process. By the time they said yes, we'd already done two or three rounds that never needed to happen.\"" },
      { type: "heading", level: 2, text: "The Turning Point" },
      { type: "paragraph", text: "The breaking point came on a residential extension project for a client in Utrecht. After three weeks of development and two rounds of external rendering — at a combined cost of roughly €2,800 — the client rejected the concept entirely. Not because the design was wrong, but because she \"couldn't picture how it would actually feel to be in that space.\"" },
      { type: "paragraph", text: "The studio had produced accurate, technically polished renders. The problem wasn't quality — it was speed and volume. The client needed to see five variations quickly to understand what she actually wanted. The studio's workflow had only allowed for two, produced slowly and expensively." },
      { type: "paragraph", text: "The studio principal spent that weekend researching AI rendering options. By Monday, they were trialing Veras, which integrates directly into Revit — the software the studio already used for all their modeling work." },
      { type: "heading", level: 2, text: "The Tools That Changed the Workflow" },
      { type: "heading", level: 3, text: "AI rendering: Veras integrated into Revit" },
      { type: "paragraph", text: "The core shift was replacing the external rendering pipeline with Veras running directly inside their existing Revit models. Instead of exporting geometry, briefing an external renderer, and waiting days for output, the team could generate photorealistic renders from their live Revit model in minutes using text prompts to control style, lighting, and atmosphere." },
      { type: "image", src: "/images/case-studies/archvision-case-study-1.webp", alt: "Architect reviewing an AI-generated building render on screen", caption: "Veras generates photorealistic renders directly from the studio's live Revit model" },
      { type: "paragraph", text: "The practical impact was immediate. For the next concept presentation — a boutique retail fit-out in Rotterdam — the team prepared twelve render variations across three design directions in a single afternoon. Different times of day, different material palettes, different levels of warmth. Variations that would previously have required three weeks and multiple external invoices were ready before the client meeting." },
      { type: "image", src: "/images/case-studies/archvision-case-study-2.webp", alt: "Boutique retail interior render with warm lighting", caption: "One of twelve AI-generated render variations produced for a single client presentation" },
      { type: "paragraph", text: "More importantly, the renders were good enough to show clients during the design process rather than only at formal presentation milestones. The studio started holding shorter, more frequent check-ins where clients could react to visual options in real time rather than waiting for a polished deck." },
      { type: "heading", level: 3, text: "AI writing: proposal and documentation drafts" },
      { type: "paragraph", text: "A secondary but meaningful time saving came from using general-purpose AI writing tools to handle the first draft of project proposals, scope documents, and planning application descriptions." },
      { type: "paragraph", text: "The studio developed a short brief template — covering project type, key design moves, client profile, and tone — that they feed into an AI writing tool before each document. The output isn't final copy, but it removes the blank-page problem and reduces the time to a first draft from several hours to under thirty minutes. Senior staff review and add the studio's specific voice and detail, rather than starting from scratch." },
      { type: "heading", level: 2, text: "The Results, Four Months Later" },
      { type: "paragraph", text: "The studio tracked results systematically across the four months following adoption." },
      { type: "stat-table", rows: [
        { label: "Average concept approval time", before: "3-4 weeks", after: "3-4 days" },
        { label: "External rendering cost per project", before: "€1,400-2,800", after: "Under €200" },
        { label: "Design variations shown per concept", before: "2-3", after: "8-12" },
        { label: "Client approval rate on first/second concept", before: "40%", after: "73%" },
        { label: "Estimated revenue impact (annualized)", before: "—", after: "+€200K" },
      ]},
      { type: "paragraph", text: "The revenue impact figure came from two sources: reduced external rendering spend across the project portfolio, and the ability to take on more projects in the same timeframe because concept phases were no longer the bottleneck." },
      { type: "paragraph", text: "The Utrecht client, whose rejection had triggered the change, was eventually brought back for a second project. This time, the concept was approved after a single two-hour session — three variations, live renders, immediate feedback, immediate decision." },
      { type: "heading", level: 2, text: "What This Means for Architecture Studios" },
      { type: "paragraph", text: "The ArchVision experience points to something broader than just \"AI renders are faster.\" The real shift is in the rhythm of client communication." },
      { type: "paragraph", text: "When renders are slow and expensive, studios conserve them — producing fewer, later in the process, at formal milestones. This means clients make large decisions with limited visual information, and feedback arrives when it's most expensive to incorporate." },
      { type: "paragraph", text: "When renders are fast and cheap, studios can share visual work earlier and more often. Clients develop their preferences gradually rather than being asked to approve or reject a finished concept. By the time a formal presentation happens, there are no surprises." },
      { type: "quote", text: "We're not producing less thoughtful work. We're just not making clients wait three weeks to tell us what they actually wanted in the first place." },
      { type: "cta", ctaText: "Browse AI tools for architecture studios", ctaLink: "/best-of/architecture" },
    ]
  },
  {
    slug: "case-study-construction-buildsmart",
    title: "How BuildSmart Saved 1,200+ Hours Monthly by Replacing Manual Takeoffs with AI",
    industry: "Construction",
    businessSize: "45-person general contractor",
    market: "Multifamily residential, North America",
    timeFrame: "6 months",
    thumbnail: "/images/case-studies/buildsmart-case-study-thumbnail.webp",
    heroImage: "/images/case-studies/buildsmart-case-study-1.webp",
    excerpt:
      "A 45-person general contractor replaced manual quantity takeoffs with AI estimating, scheduling, and site-monitoring tools — cutting takeoff time by up to 90% and more than doubling their monthly bid volume.",
    tags: ["AI tools for construction", "AI takeoff software", "Togal.AI", "construction estimating", "ALICE Technologies", "OpenSpace"],
    readingTime: "6 min",
    publishedDate: "2026-06-18",
    content: [
      { type: "paragraph", text: "In commercial construction, the margin between winning and losing a bid is rarely the price. It's the timing." },
      { type: "paragraph", text: "BuildSmart (name changed) is a 45-person general contractor based in the Pacific Northwest, specializing in multifamily residential projects in the 20–80 unit range. By most measures, they were competitive: experienced estimators, solid subcontractor relationships, and a track record that should have put them in the running for most projects they pursued." },
      { type: "heading", level: 2, text: "Losing Bids You Should Have Won" },
      { type: "paragraph", text: "But in an eight-month stretch leading into 2024, they lost four consecutive competitive bids — not because their numbers were wrong, but because they submitted late. In each case, a competing GC had submitted a complete, accurate estimate two to three days earlier. Two of the four owners had already moved forward with the early bidder before BuildSmart's submission arrived." },
      { type: "paragraph", text: "The root cause was straightforward: their estimating process was manual. Two senior estimators, working from digital PDFs, spending 60 to 80 hours per bid manually counting doors, windows, linear feet of framing, plumbing rough-in points, and dozens of other quantities across multi-story drawings. On a complex 60-unit project, a complete takeoff took the better part of two weeks." },
      { type: "paragraph", text: "\"We knew exactly what the problem was,\" the operations director said. \"We just didn't think software could actually solve it yet.\"" },
      { type: "heading", level: 2, text: "The Decision to Change" },
      { type: "paragraph", text: "After the fourth lost bid, the operations director pulled together a cost analysis. The four projects represented a combined contract value of approximately $28 million. At the firm's typical margin, winning even two of them would have covered the annual cost of almost any estimating software on the market many times over." },
      { type: "image", src: "/images/case-studies/buildsmart-case-study-1.webp", alt: "Construction estimator reviewing digital plans on a tablet", caption: "BuildSmart standardized on AI-driven quantity extraction after losing four consecutive bids to faster competitors" },
      { type: "paragraph", text: "The firm began evaluating AI-powered takeoff tools in Q1 2024. After a trial period, they standardized on Togal.AI for quantity extraction, with the plan to layer in scheduling and site monitoring tools once the estimating workflow was stable." },
      { type: "heading", level: 2, text: "The Tools That Changed the Workflow" },
      { type: "heading", level: 3, text: "AI estimating: Togal.AI for quantity takeoffs" },
      { type: "paragraph", text: "The core change was replacing manual plan counting with AI-driven quantity extraction. Estimators upload digital drawings to Togal.AI, and the system automatically detects and measures building components — doors, windows, rooms, wall lengths, and dozens of other quantities — directly from the PDF plans." },
      { type: "paragraph", text: "What previously took a senior estimator 60 to 80 hours now produces a complete first-pass takeoff in four to six hours. Estimators spend the remaining time reviewing the AI output, checking flagged items, and applying unit costs — the judgment-intensive part of their job — rather than spending most of their time counting." },
      { type: "paragraph", text: "The conversational search feature (Togal.CHAT) also changed how the team worked with unfamiliar plan sets. Instead of manually searching through 80-page drawing sets to find where a specific detail was called out, estimators can ask the system directly and get an immediate answer with a reference to the relevant drawing page." },
      { type: "heading", level: 3, text: "AI scheduling: ALICE Technologies" },
      { type: "paragraph", text: "Once the estimating workflow was running, the firm introduced ALICE Technologies for schedule generation on larger projects. Rather than manually sequencing trades and building a schedule from experience and intuition, ALICE analyzes project constraints — site access, trade dependencies, crew availability — and generates optimized schedule options." },
      { type: "paragraph", text: "For a 72-unit project completed in Q3 2024, the AI-generated schedule identified a sequencing option that reduced the projected timeline by 23 days compared to the schedule the project manager had drafted manually — by optimizing how concrete pours, framing, and MEP rough-in overlapped across the building's vertical phases." },
      { type: "heading", level: 3, text: "AI site monitoring: OpenSpace" },
      { type: "paragraph", text: "The third layer was OpenSpace for site progress tracking. Project managers mount a 360° camera to their hard hat during weekly site walks, and OpenSpace automatically maps the captured footage to the project's floor plans and BIM model. The result is a visual, timestamped record of actual site conditions that can be compared directly to the planned schedule." },
      { type: "image", src: "/images/case-studies/buildsmart-case-study-2.webp", alt: "Construction site progress tracked with a 360-degree camera", caption: "OpenSpace maps weekly site walkthroughs to the project's floor plans and BIM model" },
      { type: "paragraph", text: "This proved particularly valuable for subcontractor coordination. Rather than relying on verbal progress reports or scheduled walkthrough meetings, project managers could review site conditions remotely, identify discrepancies between actual and planned progress, and address issues before they affected the critical path." },
      { type: "heading", level: 2, text: "The Results, Six Months Later" },
      { type: "stat-table", rows: [
        { label: "Takeoff time per bid (60-unit project)", before: "60-80 hours", after: "4-6 hours" },
        { label: "Bids submitted per month", before: "3-4", after: "8-10" },
        { label: "Bid win rate", before: "22%", after: "31%" },
        { label: "Hours saved per month (estimating)", before: "—", after: "1,200+" },
        { label: "Estimated annual cost savings", before: "—", after: "$350K" },
        { label: "Schedule overrun rate", before: "34% of projects", after: "18% of projects" },
      ]},
      { type: "paragraph", text: "The 1,200 hours per month figure reflects the combined time savings across the estimating team on all active bids. The $350K annual savings estimate comes from three sources: reduced estimating labor cost, increased bid volume leading to more contract awards, and reduced schedule overrun costs on active projects." },
      { type: "paragraph", text: "The firm submitted eight bids in the first full month after stabilizing the new workflow — more than double their previous monthly volume with the same estimating team. Three were awarded contracts." },
      { type: "heading", level: 2, text: "What This Means for Construction Firms" },
      { type: "paragraph", text: "The BuildSmart story is primarily about capacity, not cost-cutting. The same two senior estimators, doing the same quality work, can now cover more than twice the bid volume. The AI handles the counting; they handle the judgment." },
      { type: "paragraph", text: "The scheduling and site monitoring tools compound this: projects are more likely to finish on time, which protects margin and builds the kind of track record that wins more bids in the first place." },
      { type: "quote", text: "The tools don't make us better estimators. They make our estimators available to actually estimate — instead of spending most of their day manually counting things a computer is faster at anyway." },
      { type: "paragraph", text: "For firms still running manual takeoffs, the math is straightforward. Every hour an estimator spends counting is an hour not spent on the analysis, scope review, and subcontractor coordination that actually requires their expertise." },
      { type: "cta", ctaText: "Browse AI tools for construction firms", ctaLink: "/best-of/construction" },
    ]
  },
  {
    slug: "case-study-interior-design-studio-nova",
    title: "How Studio Nova Shortened Client Approval from 8 Weeks to 10 Days Using AI Design Tools",
    industry: "Interior Design",
    businessSize: "Solo designer + 2 assistants",
    market: "High-end residential, United States",
    timeFrame: "4 months",
    thumbnail: "/images/case-studies/studio-nova-case-study-thumbnail.webp",
    heroImage: "/images/case-studies/studio-nova-case-study-1.webp",
    excerpt:
      "A three-person interior design studio used AI visualization and shoppable staging to compress an 8-week concept approval process down to 10 days, nearly doubling revenue per designer.",
    tags: ["AI tools for interior design", "InteriorAI", "AI room visualization", "interior design client approval", "design studio workflow"],
    readingTime: "6 min",
    publishedDate: "2026-06-14",
    content: [
      { type: "paragraph", text: "Interior design is a slow art. Clients expect it to take time. But there's a difference between a process that unfolds thoughtfully and one that simply stalls — and for a high-end residential design practice, the gap between those two things can cost you a client." },
      { type: "heading", level: 2, text: "When \"Patience\" Becomes a Business Problem" },
      { type: "paragraph", text: "Studio Nova (name changed) is a three-person interior design practice based in Austin, Texas: a principal designer with fourteen years of experience, one junior designer, and a project coordinator. Their work is high-end residential — whole-home renovations, new construction interiors, and occasional vacation property projects for repeat clients. Projects typically run between $180,000 and $600,000 in total budget, with the studio's design fee representing 15 to 18 percent of that figure." },
      { type: "paragraph", text: "By any creative measure, the studio was doing well. Their portfolio was strong. Client referrals were consistent. But a pattern had developed in their project intake that was quietly limiting their capacity and frustrating clients who came in expecting a modern, responsive design experience." },
      { type: "paragraph", text: "The concept approval phase — the period between the first design presentation and the client signing off on a direction — was averaging six to eight weeks. Multiple rounds of revised mood boards. Sourcing options that didn't quite land. Clients who said \"I love it but I'm not sure\" and needed more to react to before they could commit. And a sourcing process that required the junior designer to spend two to three days manually pulling product options from vendor catalogs after each concept revision." },
      { type: "heading", level: 2, text: "The Breaking Point" },
      { type: "paragraph", text: "The tipping point came in the form of a lost client — and a frank conversation about why." },
      { type: "image", src: "/images/case-studies/studio-nova-case-study-1.webp", alt: "Interior designer reviewing mood boards in a design studio", caption: "Studio Nova's concept approval phase was averaging six to eight weeks before adopting AI visualization" },
      { type: "paragraph", text: "A referral client had engaged the studio for a whole-home renovation project in the Hill Country. After eight weeks of back-and-forth on the primary living spaces — three presentation rounds, multiple mood board revisions, two sourcing packages — the client called to end the engagement. Her reason, delivered politely but directly: she had expected the process to be faster given the studio's fees, and she had found another designer who worked with AI visualization tools that had shown her options she could react to and decide on in the first meeting." },
      { type: "paragraph", text: "The principal designer followed up to understand what that experience had looked like. The competing designer had used an AI visualization tool to generate twelve styled room versions during a two-hour first meeting — different material palettes, different furniture configurations, different lighting moods — and the client had walked out of that meeting knowing which direction she wanted to pursue." },
      { type: "paragraph", text: "\"Eight weeks of work, and a client left because someone else showed her more options in two hours,\" the principal said. \"That was the moment I stopped thinking AI visualization was optional.\"" },
      { type: "heading", level: 2, text: "The Tools That Changed the Workflow" },
      { type: "heading", level: 3, text: "AI visualization: concept exploration at the speed of conversation" },
      { type: "paragraph", text: "The studio began evaluating AI interior design tools and settled on InteriorAI as the primary option for early-stage concept visualization — uploading reference photos or room images and generating styled versions across different aesthetics quickly enough to use during client meetings." },
      { type: "paragraph", text: "The workflow change was significant. Instead of preparing a polished mood board between meetings and presenting it at a formal milestone, the principal designer now begins client conversations with a visual exploration session. A client mentions they're drawn to \"warmth but not traditional\" — the designer generates four or five variations on screen, the client reacts, the designer narrows, generates more specific options, and within an hour there's a clear direction that previously would have taken two or three rounds of offline preparation to arrive at." },
      { type: "image", src: "/images/case-studies/studio-nova-case-study-2.webp", alt: "AI-generated styled living room visualization", caption: "AI visualization tools let clients react to multiple styled directions within a single meeting" },
      { type: "paragraph", text: "The visual quality of these early-stage explorations isn't portfolio-ready. But that's not the point. The point is giving clients enough to react to that they can make decisions rather than staying stuck in vague preference territory." },
      { type: "heading", level: 3, text: "AI shoppable staging: closing the gap between concept and product" },
      { type: "paragraph", text: "The second problem was sourcing time. After each concept round, the junior designer would spend two to three days manually pulling furniture, textiles, and lighting options from vendor catalogs — cross-referencing lead times, checking client budget parameters, and assembling options into a presentation format." },
      { type: "paragraph", text: "The studio began using AI staging tools with shoppable product integration to accelerate this process. Rather than sourcing from scratch, the AI generates a styled room with furniture options linked to real, purchasable products — giving the junior designer a starting point to refine rather than a blank slate to fill. The manual curation and client-specific adjustment still happens, but the two-to-three-day sourcing process has compressed to four to six hours." },
      { type: "heading", level: 3, text: "AI writing: proposals and project documentation" },
      { type: "paragraph", text: "A smaller but consistent time saving came from using AI writing tools for project proposals, scope-of-work documents, and client-facing milestone summaries. The studio developed a brief template covering project scope, design intent, key parameters, and client profile — and uses it to generate first drafts that the principal reviews and personalizes before sending." },
      { type: "paragraph", text: "For a practice where the principal designer was previously writing most client communications herself, this removed several hours of administrative writing per project per week." },
      { type: "heading", level: 2, text: "The Results, Four Months Later" },
      { type: "stat-table", rows: [
        { label: "Average concept approval time", before: "6-8 weeks", after: "8-10 days" },
        { label: "Sourcing time per concept round", before: "2-3 days", after: "4-6 hours" },
        { label: "Design directions shown in first meeting", before: "1-2", after: "8-12" },
        { label: "Projects active simultaneously", before: "3", after: "5" },
        { label: "Revenue per designer (annualized)", before: "baseline", after: "~2x" },
        { label: "Client satisfaction score", before: "7.8/10", after: "9.1/10" },
      ]},
      { type: "paragraph", text: "The capacity increase — from three to five concurrent active projects with the same team — was the largest financial impact. At the studio's average design fee, one additional concurrent project represents roughly $35,000 to $80,000 in additional annual revenue per project slot added." },
      { type: "paragraph", text: "Client satisfaction scores also improved, which the principal attributed not to the AI tools themselves but to the change in client experience: faster feedback loops, more options to react to, and less time spent in the ambiguous \"waiting to see what they come back with\" phase that clients find frustrating regardless of the final output quality." },
      { type: "heading", level: 2, text: "What This Means for Interior Design Studios" },
      { type: "paragraph", text: "The Studio Nova story is ultimately about the pace of collaboration. Clients in the high-end residential market are paying significant fees and have high expectations for responsiveness. A process that requires weeks between touchpoints — even when the work in between is excellent — can feel out of step with those expectations." },
      { type: "paragraph", text: "AI visualization tools don't change the designer's creative judgment. They change how quickly that judgment can be communicated and tested. The difference between showing a client two options after two weeks and showing them twelve options in the first meeting isn't about working less carefully — it's about removing the production time between the idea and the image." },
      { type: "quote", text: "I spent fourteen years learning to understand what clients actually want. The AI didn't change that skill. It just stopped making them wait six weeks while I translated it into something they could see." },
      { type: "cta", ctaText: "Browse AI tools for interior design studios", ctaLink: "/best-of/interior-design" },
    ]
  },
  {
    slug: "case-study-real-estate-prime-realty",
    title: "How Prime Realty Generated 3x More Qualified Leads with AI Marketing and 24/7 Lead Response",
    industry: "Real Estate",
    businessSize: "Boutique brokerage, 12 agents",
    market: "Residential mid-to-luxury, North America",
    timeFrame: "5 months",
    thumbnail: "/images/case-studies/prime-realty-case-study-thumbnail.webp",
    heroImage: "/images/case-studies/prime-realty-case-study-1.webp",
    excerpt:
      "A 12-agent boutique brokerage used AI lead nurture, virtual staging, and copywriting tools to triple qualified leads per month and cut lead response time from over 4 hours to under 10 minutes.",
    tags: ["AI tools for real estate", "real estate lead generation", "Ylopo AI", "virtual staging AI", "real estate marketing automation"],
    readingTime: "6 min",
    publishedDate: "2026-06-12",
    content: [
      { type: "paragraph", text: "In residential real estate, a lead that doesn't hear back within the first hour is usually a lead that hires someone else." },
      { type: "heading", level: 2, text: "The Leads That Got Away" },
      { type: "paragraph", text: "Prime Realty (name changed) is a boutique brokerage operating in a mid-to-luxury residential market in the Pacific Northwest, with 12 agents covering a competitive market where the median transaction value sits above $850,000. The firm had built a solid reputation over eight years — repeat clients, strong referral rates, and a handful of agents consistently in the top 20% of the local market." },
      { type: "paragraph", text: "But in the spring of 2024, the managing broker pulled together three months of lead data and found a pattern she hadn't expected. Of the 94 inbound leads the brokerage had received through their website and property inquiry forms, 31 had gone more than four hours without a response. Of those 31, only three had eventually converted to clients. The remaining 28 had either gone cold or, in seven confirmed cases, ended up working with a competitor." },
      { type: "paragraph", text: "The math was stark. At the brokerage's average commission on a transaction in their market, those 28 leads represented somewhere between $400,000 and $700,000 in lost gross commission income over a single quarter." },
      { type: "paragraph", text: "\"We weren't losing business because we weren't good enough,\" the managing broker said. \"We were losing it because nobody was awake at 10pm on a Saturday when someone decided they wanted to see a listing.\"" },
      { type: "heading", level: 2, text: "The Turning Point" },
      { type: "paragraph", text: "The brokerage's website was generating meaningful inbound traffic — a combination of SEO, a modest Google Ads budget the managing broker managed herself, and word of mouth from past clients. But the lead capture experience was a standard contact form, and follow-up depended entirely on which agent happened to be checking their email." },
      { type: "image", src: "/images/case-studies/prime-realty-case-study-1.webp", alt: "Real estate agent reviewing inbound leads on a laptop", caption: "Prime Realty traced $400K-$700K in lost commission to leads that went unanswered for over four hours" },
      { type: "paragraph", text: "After reviewing the lost lead data, the managing broker identified three separate problems: slow initial response, inconsistent follow-up cadence, and listing presentations that weren't converting as well as they should — in part because listing photos on several mid-range properties weren't showing the spaces at their best." },
      { type: "paragraph", text: "She began evaluating solutions for each problem separately, eventually landing on a stack of three AI tools that addressed them in sequence." },
      { type: "heading", level: 2, text: "The Tools That Changed the Workflow" },
      { type: "heading", level: 3, text: "AI lead response: Ylopo for 24/7 nurture" },
      { type: "paragraph", text: "The first and most urgent fix was lead response. The brokerage implemented Ylopo's AI-powered text and email nurture system to handle initial outreach the moment a lead came in — regardless of time of day or whether an agent was available." },
      { type: "paragraph", text: "When a prospective buyer submits an inquiry through the brokerage's website, Ylopo initiates a text conversation within minutes, asking qualifying questions about timeline, budget range, and what they're looking for. By the time a human agent picks up the conversation — usually within business hours the following day — there's already a qualified profile attached to the lead rather than just a name and phone number." },
      { type: "paragraph", text: "The system also handles follow-up cadence for leads that don't respond immediately, sending a structured sequence of messages over the following days without requiring agent involvement. The tone is conversational rather than templated, which reduced the opt-out rate compared to the firm's previous email drip sequences." },
      { type: "heading", level: 3, text: "AI virtual staging: faster, more affordable listing presentation" },
      { type: "paragraph", text: "The second problem — listing photos that undersold the space — was addressed with AI virtual staging. For vacant or sparsely furnished properties, the brokerage began using AI staging tools to produce furnished room images from empty property photos." },
      { type: "image", src: "/images/case-studies/prime-realty-case-study-2.webp", alt: "Virtually staged living room generated by AI", caption: "AI virtual staging cut a five-room staging package from $500-700 with a week's lead time to under $100 with same-day turnaround" },
      { type: "paragraph", text: "Traditional virtual staging through a design service typically costs $75 to $150 per room and takes two to four business days. AI staging tools reduced both the cost and turnaround time significantly — producing multiple style options per room in hours rather than days. For a five-room property, the full staging package went from a $500–700 expense with a week's lead time to under $100 with same-day turnaround." },
      { type: "paragraph", text: "The staged images were used for MLS listings, the brokerage website, and paid social campaigns — and the managing broker tracked a measurable increase in showing requests on properties where AI staging was used compared to equivalent listings with empty room photos." },
      { type: "heading", level: 3, text: "AI copywriting: listing descriptions and campaign content" },
      { type: "paragraph", text: "The third piece was content volume. With 12 active agents, the brokerage was producing listing descriptions, email campaigns, social posts, and property feature sheets continuously — most of it written by agents or the managing broker herself, eating into time that could have been spent on client work." },
      { type: "paragraph", text: "The brokerage developed a brief template for each listing — covering property type, key features, neighborhood context, and target buyer profile — and began using ChatGPT to produce first drafts. Agents review and personalize the output before publishing, but the blank-page problem is gone. A listing description that previously took 45 to 60 minutes to write from scratch now takes 10 to 15 minutes to review and refine." },
      { type: "heading", level: 2, text: "The Results, Five Months Later" },
      { type: "stat-table", rows: [
        { label: "Average lead response time", before: "4+ hours", after: "Under 10 minutes" },
        { label: "Lead-to-consultation conversion rate", before: "18%", after: "41%" },
        { label: "Qualified leads per month", before: "31", after: "94" },
        { label: "Cost per qualified lead", before: "$185", after: "$92" },
        { label: "Showing requests, staged vs. unstaged", before: "—", after: "+38%" },
        { label: "Pipeline value (active leads)", before: "$1.8M", after: "$4.7M" },
      ]},
      { type: "paragraph", text: "The tripling of qualified leads came from two sources: improved conversion on existing inbound traffic (same volume of leads, but more converting to consultations due to faster, more consistent follow-up) and an increase in listing inquiries driven by better visual presentation." },
      { type: "paragraph", text: "The revenue impact reflects closed transactions in the five months following implementation that the managing broker directly attributed to leads that would previously have gone cold without a response." },
      { type: "heading", level: 2, text: "What This Means for Real Estate Teams" },
      { type: "paragraph", text: "The Prime Realty experience is a story about response infrastructure, not just marketing. Most boutique brokerages already have enough inbound interest to grow — the bottleneck is the gap between a lead arriving and a human agent picking up the conversation." },
      { type: "paragraph", text: "AI lead nurture tools don't replace the agent relationship. They ensure the relationship gets a chance to start. The virtual staging and copywriting tools are about efficiency — allowing the same team to handle more listings at the same quality level rather than hiring more staff or working more hours." },
      { type: "quote", text: "We're not doing anything dramatically different in terms of how we work with clients. We're just not losing the ones who came to us first anymore." },
      { type: "cta", ctaText: "Browse AI tools for real estate teams", ctaLink: "/best-of/real-estate" },
    ]
  }
];
